### ISSUE TITLE
Badge number setOverlayIcon

### ISSUE THREAD

**Issue by asmith20002** [alexmercerind/windows_taskbar#11]
setOverlayIcon() requires an icon.  If I want to show unread messages as number badge. Should I make an icon for each number?

```
WindowsTaskbar.setOverlayIcon(
  ThumbnailToolbarAssetIcon('assets/red_slash.ico'),
  tooltip: 'Stop',
);
```

**Comment by alexmercerind** [comment]
I believe you have to make an icon. There's no way to show text.
