### ISSUE TITLE
Support for taskbar widgets

### ISSUE THREAD

**Issue by Borouch** [alexmercerind/windows_taskbar#12]
A feature to add window taskbar widget with flutter desktop would be amazing. An example would be weather widget that is optionaly displayed on the right corner of taskbar (before system tray icons).

![image](https://user-images.githubusercontent.com/60584457/180322662-2d3dd7e7-090a-4f94-8d7b-3f95c79d77ba.png)

**Comment by alexmercerind** [comment]
It's not a public API for developers from Microsoft/Windows.
Neither it's a "widget".
Similar request exists at #2.
A solution can be to place a topmost frameless window at bottom-left of the screen. Beyond the scope of this plugin.

Thanks!
