### ISSUE TITLE
Add Support for linux and Macos

### ISSUE THREAD

**Issue by stMerlHin** [alexmercerind/windows_taskbar#14]
This plugin is very awesome, Is there a plan for adding support for linux and Macos ?

**Comment by alexmercerind** [comment]
Hi,

What specifically? GNU/Linux or macOS don't even have a taskbar.

The features offered by this plugin are part of Microsoft Windows only e.g. taskbar progress state, thumbnail toolbar buttons or icon badge etc.

Even if macOS or GNU/Linux offer some similar equivalent system API for one or two features present in this plugin, most features will be just missing. Another problem of implementing features specific to those OSes will also be raised.

The plugin's name even has the word "`windows`" in it.

Best is to create another package(s) which deals with the specifics of that operating system(s). The features offered here are specific to Microsoft Windows's 


Thanks!
