### ISSUE TITLE
app windows shows not responding when close app (using with lib bitsdojo window)

### ISSUE THREAD

**Issue by thaidmfinnick** [alexmercerind/windows_taskbar#15]
Hi, @alexmercerind 

I've used `windows_taskbar` lib to show overlayIcon recently. It works very well but after I install `windows_taskbar` lib in my pubspec.yaml, when I tap to close button in my app (or right click app in taskbar), app doesn't close immediately, shows not responding then closes after 5-7 seconds (sometimes 15 seconds):

![image](https://github.com/alexmercerind/windows_taskbar/assets/83997264/7d77b9fe-0114-4e9c-9a7a-81281913f1c5)

I try to disable `windows_taskbar` in pubspec.yaml and I can close without any problem. I use `bitsdojo_window` for buttons (minimize, maximize, close). 

I've checked issues in `windows_taskbar` issues on github and have known that someone still met problems when combining 2 libs (bitsdojo and windows_taskbar). 

Have you met this problem in any case? I can't find where's problem.

Very looking for your response! Many thanks!

**Comment by shuax** [comment]
Because of the missing call to `RegisterTopLevelWindowProcDelegate` in the `WindowsTaskbarPlugin` destructor

**Comment by thaidmfinnick** [comment]
Thanks @shuax for your reply! You mean when I call `UnregisterTopLevelWindowProcDelegate` in destructor and the problem will be solved, won't you?

**Comment by shuax** [comment]
> Thanks @shuax for your reply! You mean when I call `UnregisterTopLevelWindowProcDelegate` in destructor and the problem will be solved, won't you?

yes, I referred to https://github.com/leanflutter/window_manager/blob/36f34eadbe0a7fe0c589052f537ef1bcb502835c/windows/window_manager_plugin.cpp#L94

**Comment by thaidmfinnick** [comment]
wow, work perfectly, really thanks and huge respect to @shuax, I had to hide this lib from my project because of this error. Now, everything works together kk. I will close this issue as completed!

**Comment by alexmercerind** [comment]
Please do consider submitting a PR if possible.

**Comment by alexmercerind** [comment]
[I've published an update.](https://pub.dev/packages/windows_taskbar)

Thanks!
