### ISSUE TITLE
Embed the form in the taskbar

### ISSUE THREAD

**Issue by yhsj0919** [alexmercerind/windows_taskbar#2]
like this
![image](https://user-images.githubusercontent.com/7219412/145915811-a2eda91a-70a1-40a8-86b2-87f8f4935401.png)

**Comment by alexmercerind** [comment]
Can you explain more? Or show the complete screenshot? I'm confused where does it belong?

**Comment by yhsj0919** [comment]
![image](https://user-images.githubusercontent.com/7219412/145944708-ac0f5e14-ff2c-4379-86b0-cfd563bf19e3.png)
