### ISSUE TITLE
Feature request: Flash taksbar

### ISSUE THREAD

**Issue by dimio5** [alexmercerind/windows_taskbar#4]
Awesome plugin, thanks so much for this!!

It would be really helpful if there was support to programmatically flash the task bar.

The use case for me is to draw users attention when something needs to be approved/rejected or fixed manually, while in normal cases it would be processed automatically.

I am not familiar with c++ unfortunately, if I could use dotnet I'd use something like this: https://stackoverflow.com/a/4889227

Do you think it's worth supporting in this library?

**Comment by alexmercerind** [comment]
Hello @dimio5,

I know it's been a long time, but I have added this feature with latest [v0.0.1](https://github.com/alexmercerind/windows_taskbar/releases/tag/v1.0.0) release.

**Flash windows taskbar app icon**

```dart
// More options are available in the plugin API.

WindowsTaskbar.flashTaskbarAppIcon(
  mode: TaskbarFlashMode.all | TaskbarFlashMode.timernofg,
  timeout: const Duration(milliseconds: 500),
);
```

**Stop flashing windows taskbar app icon**

```dart
WindowsTaskbar.stopFlashingTaskbarAppIcon();
```


Thankyou!

**Comment by dimio5** [comment]
That's awesome!! 
Will test asap, thank you
