### ISSUE TITLE
ThumbnailToolbarButton does not work properly with bitsdojo_window

### ISSUE THREAD

**Issue by f-ever** [alexmercerind/windows_taskbar#7]
Sometimes, WindowsTaskbar.setThumbnailToolbar does not work properly when [bitsdojo_window](https://pub.dev/packages/bitsdojo_window)  is enabled.

![1](https://user-images.githubusercontent.com/51989258/153908732-9f58a3eb-983a-4bcf-9cac-f6578e55a208.png)

```
Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.22543.1000], locale zh-CN)
windows_taskbar: ^1.1.0
bitsdojo_window: ^0.1.1+1
```

**Comment by f-ever** [comment]
> The plugin is being used in [Harmonoid](https://github.com/harmonoid/harmonoid). Never noticed any problem, infact the controls are changed very often according to playlist.

I know it works fine in Harmonoid, in my own project, it was fine yesterday, but ThumbnailToolbar suddenly won't show up today and I don't know what happened. So I cloned the windows_taskbar repo. In the example project, when I just import bitsdojo_window, the ThumbnailToolbar works fine, but when I add ```auto bdw = bitsdojo_window_configure(BDW_CUSTOM_FRAME | BDW_HIDE_ON_STARTUP);``` to windows\runner\main.cpp, the ThumbnailToolbar disappears.

**Comment by alexmercerind** [comment]
> > The plugin is being used in [Harmonoid](https://github.com/harmonoid/harmonoid). Never noticed any problem, infact the controls are changed very often according to playlist.
> 
> I know it works fine in Harmonoid, in my own project, it was fine yesterday, but ThumbnailToolbar suddenly won't show up today and I don't know what happened. So I cloned the windows_taskbar repo. In the example project, when I just import bitsdojo_window, the ThumbnailToolbar works fine, but when I add `auto bdw = bitsdojo_window_configure(BDW_CUSTOM_FRAME | BDW_HIDE_ON_STARTUP);` to windows\runner\main.cpp, the ThumbnailToolbar disappears.

Harmonoid also uses bitsdojo_window & it works great. Possibly you should try to match the order of function calls etc. I will test in detail tomorrow, for now I don't see anything wrong.

**Comment by f-ever** [comment]
Problem solved, the first setThumbnailToolbar must be called after doWhenWindowReady.
