### ISSUE TITLE
please support more platform, especially the mac os

### ISSUE THREAD

**Issue by imjakey** [alexmercerind/windows_taskbar#9]
please support more platform, especially the mac os, thanks very much!

**Comment by alexmercerind** [comment]
Sorry I can't afford a mac.

**Comment by imjakey** [comment]
> 

Maybe you can use virtualbox or any other vm software to create an mac development environment.

**Comment by alexmercerind** [comment]
Setting up a hackintosh VM isn't easy unfortunately. I tried running it one day & booted into it successfully aswell.
However, having no hardware acceleration to run a Flutter app & no useable performance to setup/use compilation tools & Flutter SDK is a big pain. 
I ask community to work on this feature.

**Comment by raj457036** [comment]
@alexmercerind you can try this one

https://pub.dev/packages/macos_user_attention

or 

https://github.com/raj457036/macos_user_attention
